# -*- coding: utf-8 -*-
"""Copia di AnimatedStock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zp8CtW2r6cNFTZkM0YePUav7Vsy5Pl11
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import time
import random
from datetime import datetime, timedelta

# Set the title of the Streamlit app
st.title("Stock Prices with Animation")


data = {
    'name': [
        'Apple', 'Alphabet', 'Microsoft', 'Amazon', 'NVIDIA', 'Meta', 'Tesla',
        'Berkshire Hathaway', 'Eli Lilly', 'Visa', 'Broadcom', 'JPMorgan Chase',
        'UnitedHealth', 'Walmart', 'Mastercard', 'Exxon Mobil', 'Johnson & Johnson',
        'Procter & Gamble', 'Home Depot', 'Costco', 'Chevron', 'Bank of America',
        'Pfizer', 'Walt Disney', 'PayPal', 'Verizon', 'Intel', 'Coca-Cola',
        'Wells Fargo', 'AT&T', 'General Electric', 'Oracle', 'Citigroup', 'IBM',
        'Philip Morris Int.', 'Cisco Systems', 'Merck', 'PepsiCo', 'AIG', 'Amgen',
        'UPS', 'Bristol-Myers Squibb', 'Qualcomm', 'Loews', 'Raytheon', 'McDonald’s',
        'Boeing', '3M', 'Altria Group'
    ],
    'ticker': [
        'AAPL', 'GOOG', 'MSFT', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK-A', 'LLY', 'V',
        'AVGO', 'JPM', 'UNH', 'WMT', 'MA', 'XOM', 'JNJ', 'PG', 'HD', 'COST', 'CVX',
        'BAC', 'PFE', 'DIS', 'PYPL', 'VZ', 'INTC', 'KO', 'WFC', 'T', 'GE', 'ORCL',
        'C', 'IBM', 'PM', 'CSCO', 'MRK', 'PEP', 'AIG', 'AMGN', 'UPS', 'BMY', 'QCOM',
        'L', 'RTX', 'MCD', 'BA', 'MMM', 'MO'
    ],
   'ipo': [1980, 2004, 1986, 1997, 1999, 2012, 2010, 1965, 1952, 2008, 2009, 1969, 1984, 1970, 2006, 1972, 1944, 1890, 1981, 1985, 1926, 1971, 1942, 1957, 2002, 2000, 1971, 1919, 1978, 1984, 1892, 1986, 1986, 1916, 2008, 1990, 1970, 1965, 1969, 1983, 1999, 1933, 1991, 1969, 1980, 1965, 1962, 1946, 2008]
}


# Converte i dati in un DataFrame
df = pd.DataFrame(data)
# Inizializza un DataFrame vuoto per raccogliere i dati
combined_data = pd.DataFrame()

# Create input fields for stock symbols and moving averages

# Menu a tendina per selezionare più titoli

stock_input = st.multiselect("Select stocks:", options=df['name'])
selected_stocks = df[df['name'].isin(stock_input)]
selected_tickers = selected_stocks['ticker']
selected_stock = selected_tickers

max_ipo_year = selected_stocks['ipo'].max()+1  # Anno di IPO più recente
#max_ipo_year = 2024  # Anno di IPO più recente

def random_3_years(max_ipo_year):  # Pass max_ipo_year as parameter
    # Get yesterday's date
    yesterday = datetime.today() - timedelta(days=1)
    
    # Create start date from max_ipo_year
    start_boundary = datetime(max_ipo_year, 1, 1)
    
    # Calculate the latest possible start date (3 years before yesterday)
    latest_start = yesterday - timedelta(days=3*365)
    
    # Generate random start date between max_ipo_year and latest possible start
    days_range = (latest_start - start_boundary).days
    if days_range < 0:
        raise ValueError("max_ipo_year is too recent to allow for a 3-year period up to yesterday")
    
    random_start = start_boundary + timedelta(days=random.randint(0, days_range))
    random_end = random_start + timedelta(days=3*365)
    
    return random_start.strftime('%Y-%m-%d'), random_end.strftime('%Y-%m-%d')
    
start_date, end_date = random_3_years(max_ipo_year)

st.write(start_date, end_date)

for ticker in selected_tickers:
    # Fetch stock data for the selected symbol
        stock = yf.Ticker(ticker)
        #hist = stock.history(start="2019-02-01", interval="1wk") #funzionante, prob non riesce a fre grafici con troppi punti
        #hist = stock.history(period="max",interval="1wk" ) #funzionante
        #hist1 = stock.history(start=f"{max_ipo_year}-01-01",interval="1wk" )
        hist1 = stock.history(start=start_date,end=end_date,interval="1wk" )
       

        hist1.reset_index(inplace=True)
        hist1['Ticker'] = ticker  # Aggiunge una colonna per identificare il titolo
        combined_data = pd.concat([combined_data, hist1])
    
# Resetta l'indice per spostare la colonna 'Date' nell'asse principale
combined_data.reset_index(inplace=True)

sp = yf.Ticker('^GSPC')
#sp500_data=sp.history(start=f"{max_ipo_year}-01-01",interval="1wk" )
sp500_data=sp.history(start=start_date, end=end_date, interval="1wk" )
sp500_data = sp500_data[['Close']]  # Mantieni solo la colonna 'Close'
# Calcola la variazione percentuale per l'S&P 500
sp500_data['returns']=sp500_data['Close'].pct_change()
sp500_data['Percent Change'] = (sp500_data['Close'] - sp500_data['Close'][0]) / sp500_data['Close'][0] * 100

st.write("Ecco un'anteprima di sp500_data:")
st.dataframe(sp500_data)
# Reimposta l'indice e aggiungi la colonna "Date"
sp500_data.reset_index(inplace=True)
st.write("Ecco un'anteprima di sp500_data_indexed:")
st.dataframe(sp500_data)

st.write("Ecco un'anteprima di combined_data:")
st.dataframe(combined_data)

   # Calcola il numero di titoli
num_tickers = len(selected_tickers)
st.write(num_tickers)
# Calcola i ritorni settimanali per ogni ticker
# Calculate weekly returns for each ticker
combined_data['Return'] = combined_data.groupby('Ticker')['Close'].pct_change()

# Pivot the returns table
returns = combined_data.pivot_table(
    index='Date',
    columns='Ticker',
    values='Return',
)

# Fill any NaN values with 0 to handle missing data
returns = returns.fillna(0)

st.write("Ecco un'anteprima di returns:")
st.dataframe(returns)


# Calculate the equally weighted portfolio returns
portfolio_weights = [1/num_tickers] * num_tickers
portfolio_returns = (returns * portfolio_weights).sum(axis=1)

# Calculate cumulative returns properly using compound returns formula
portfolio_cumulative_returns = (1 + portfolio_returns).cumprod() - 1

# Convert to percentage
portfolio_cumulative_returns = portfolio_cumulative_returns * 100

# Convert to DataFrame with proper date index
hist = pd.DataFrame(portfolio_cumulative_returns)
hist.reset_index(inplace=True)
hist.columns = ["Date", "Close"]

st.write("Ecco un'anteprima di hist:")
st.dataframe(hist)





    # Create the base figure
fig = go.Figure()

    # Create frames for animation
frames = [
        go.Frame(
            data=[
                go.Scatter(x=hist['Date'][:k+1], y=hist['Close'][:k+1], mode='lines', name='Close Price'),
                go.Scatter(x=sp500_data['Date'][:k+1], y=sp500_data['Percent Change'][:k+1], mode='lines',
                          name='SP500', line=dict(dash='dot')),
            ],
            name=str(k)
        ) for k in range(len(hist))
    ]

    # Add the first frame manually to ensure the initial display
fig.add_trace(go.Scatter(x=hist['Date'][:1], y=hist['Close'][:1], mode='lines', name='Perf %'))
fig.add_trace(go.Scatter(x=sp500_data['Date'][:1], y=sp500_data['Percent Change'][:1], mode='lines', name='SP500', line=dict(dash='dot')))    

# Calcola il range per l'asse x e y
y_min = min(hist['Close'].min(), sp500_data['Percent Change'].min())
y_max = max(hist['Close'].max(), sp500_data['Percent Change'].max())
y_min
y_max

    # Update the layout with frames and animation settings
fig.update_layout(
        #xaxis=dict(range=[hist['Date'].min(), hist['Date'].max()], title='Date'),
        #yaxis=dict(range=[sp500_data['Percent Change'].min(), sp500_data['Percent Change'].max()], title='Perf %'),
        xaxis=dict(range=[hist['Date'].min(), hist['Date'].max()], title='Date'),
        yaxis=dict(range=[y_min, y_max], title='Perf %'),
    
        title=f"{stock_input} Equally weighted portfolio vs S&P500 index",
        updatemenus=[dict(type="buttons", showactive=False,
                          buttons=[dict(label="Play",
                                        method="animate",
                                        args=[None, {"frame": {"duration": 1, "redraw": False},
                                                     "fromcurrent": True, "mode": "immediate"}])])],
        sliders=[{
            "steps": [{"args": [[str(k)], {"frame": {"duration": 1, "redraw": False}, "mode": "immediate"}],
                       "label": str(hist['Date'][k].date()), "method": "animate"} for k in range(len(hist))],
            "transition": {"duration": 0},
            "x": 0.1,
            "len": 0.9
        }]
    )

    # Add frames to the figure
fig.frames = frames

    # Display the Plotly figure in Streamlit
st.plotly_chart(fig)

# Display additional stock information
with st.expander("Stock Information"):
        info = stock.info
        st.write(f"**Company Name:** {info.get('longName', 'N/A')}")
        st.write(f"**Sector:** {info.get('sector', 'N/A')}")
        st.write(f"**Industry:** {info.get('industry', 'N/A')}")
        st.write(f"**Current Price:** ${info.get('currentPrice', 'N/A')}")
        st.write(f"**Market Cap:** ${info.get('marketCap', 'N/A'):,}")
        st.write(f"**52 Week High:** ${info.get('fiftyTwoWeekHigh', 'N/A')}")
        st.write(f"**52 Week Low:** ${info.get('fiftyTwoWeekLow', 'N/A')}")
# Display moving average crossover analysis
with st.expander("Perf Analysis"):
        # Calculate latest values
        hist_perf = hist['Close'].iloc[-1]
        sp500_data_perf = sp500_data['Percent Change'].iloc[-1]

        hist_perf = hist['Close'].iloc[-1]
        sp500_data_ini = sp500_data['Close'].iloc[0]
        sp500_data_fin = sp500_data['Close'].iloc[-1]

        

        st.write(f"**Latest Values:**")
        st.write(f"Performance Portfolio: {hist_perf:.2f}%")
        st.write(f"Performance S&P500: {sp500_data_perf:.2f}%")
        st.write(f"Initial Index value S&P500: {sp500_data_ini:.2f} pt")
        st.write(f"Final Index value S&P500: {sp500_data_fin:.2f} pt")




        # Analyze crossovers
        #if latest_ma1 > latest_ma2:
            #st.write(f"🔼 The {ma1_name} is currently above the {ma2_name}, suggesting bullish momentum.")
        #else:
            #st.write(f"🔽 The {ma1_name} is currently below the {ma2_name}, suggesting bearish momentum.")

 

