# -*- coding: utf-8 -*-
"""Copia di AnimatedStock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zp8CtW2r6cNFTZkM0YePUav7Vsy5Pl11
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go

# Set the title of the Streamlit app
st.title("Stock Prices with Animation")

# Create input fields for stock symbols and moving averages

stock_input = st.text_input("Enter stock symbols (comma-separated)")





# Process the input string to get a list of stock symbols
stock_symbols = [symbol.strip().upper() for symbol in stock_input.split(",")]

# Create a selection box for choosing which stock to display
selected_stock = st.selectbox("Select stock to display", stock_symbols)


try:
    # Fetch stock data for the selected symbol
    stock = yf.Ticker(selected_stock)
    hist = stock.history(period="1mo")

    # Reset index to get 'Date' as a column
    hist.reset_index(inplace=True)



    st.write("Ecco un'anteprima di hist:")
    st.dataframe(hist)

    # Create the base figure
    fig = go.Figure()

    # Create frames for animation
    frames = [
        go.Frame(
            data=[
                go.Scatter(x=hist['Date'][:k+1], y=hist['Close'][:k+1], mode='lines', name='Close Price')
            ],
            name=str(k)
        ) for k in range(len(hist))
    ]

    # Add the first frame manually to ensure the initial display
    fig.add_trace(go.Scatter(x=hist['Date'][:1], y=hist['Close'][:1], mode='lines', name='Close Price'))
    

    # Update the layout with frames and animation settings
    fig.update_layout(
        xaxis=dict(range=[hist['Date'].min(), hist['Date'].max()], title='Date'),
        yaxis=dict(range=[hist['Close'].min(), hist['Close'].max()], title='Price ($)'),
        title=f"{selected_stock} Share Prices with",
        updatemenus=[dict(type="buttons", showactive=False,
                          buttons=[dict(label="Play",
                                        method="animate",
                                        args=[None, {"frame": {"duration": 20, "redraw": True},
                                                     "fromcurrent": True, "mode": "immediate"}])])],
        sliders=[{
            "steps": [{"args": [[str(k)], {"frame": {"duration": 1, "redraw": True}, "mode": "immediate"}],
                       "label": str(hist['Date'][k].date()), "method": "animate"} for k in range(len(hist))],
            "transition": {"duration": 0},
            "x": 0.1,
            "len": 0.9
        }]
    )

    # Add frames to the figure
    fig.frames = frames

    # Display the Plotly figure in Streamlit
    st.plotly_chart(fig)

   
except Exception as e:
    st.error(f"Error fetching data for {selected_stock}. Please check the stock symbol and try again.")
    st.error(f"Error details: {str(e)}")
