# -*- coding: utf-8 -*-
"""Copia di AnimatedStock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zp8CtW2r6cNFTZkM0YePUav7Vsy5Pl11
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go

# Set the title of the Streamlit app
st.title("Try to beat the market")


#data = {'name': ['Apple', 'Alphabet', 'Microsoft', 'Amazon', 'NVIDIA', 'Meta', 'Tesla', 'Berkshire Hathaway', 'Eli Lilly', 'Visa', 'Broadcom', 'JPMorgan Chase', 'UnitedHealth', 'Walmart', 'Mastercard', 'Exxon Mobil', 'Johnson & Johnson', 'Procter & Gamble', 'Home Depot', 'Costco', 'Chevron', 'Bank of America', 'Pfizer', 'Walt Disney', 'PayPal', 'Verizon', 'Intel', 'Coca-Cola', 'Wells Fargo', 'AT&T', 'General Electric', 'Oracle', 'Citigroup', 'IBM', 'Philip Morris Int.', 'Cisco Systems', 'Merck', 'PepsiCo', 'AIG', 'Amgen', 'UPS', 'Bristol-Myers Squibb', 'Qualcomm', 'Loews', 'Raytheon', 'McDonald’s', 'Boeing', '3M', 'Altria Group'], 'ticker': ['AAPL', 'GOOG', 'MSFT', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK-B', 'LLY', 'V', 'AVGO', 'JPM', 'UNH', 'WMT', 'MA', 'XOM', 'JNJ', 'PG', 'HD', 'COST', 'CVX', 'BAC', 'PFE', 'DIS', 'PYPL', 'VZ', 'INTC', 'KO', 'WFC', 'T', 'GE', 'ORCL', 'C', 'IBM', 'PM', 'CSCO', 'MRK', 'PEP', 'AIG', 'AMGN', 'UPS', 'BMY', 'QCOM', 'L', 'RTX', 'MCD', 'BA', 'MMM', 'MO'], 'ipo': [1980, 2004, 1986, 1997, 1999, 2012, 2010, 1965, 1952, 2008, 2009, 1969, 1984, 1970, 2006, 1972, 1944, 1890, 1981, 1985, 1926, 1971, 1942, 1957, 2002, 2000, 1971, 1919, 1978, 1984, 1892, 1986, 1986, 1916, 2008, 1990, 1970, 1965, 1969, 1983, 1999, 1933, 1991, 1969, 1980, 1965, 1962, 1946, 2008]}

# Lista di titoli
#stocks = ['Apple', 'Alphabet', 'Microsoft', 'Amazon', 'NVIDIA', 'Meta', 'Tesla', 'Berkshire Hathaway', 'Eli Lilly', 'Visa', 'Broadcom', 'JPMorgan Chase', 'UnitedHealth', 'Walmart', 'Mastercard', 'Exxon Mobil', 'Johnson & Johnson', 'Procter & Gamble', 'Home Depot', 'Costco', 'Chevron', 'Bank of America', 'Pfizer', 'Walt Disney', 'PayPal', 'Verizon', 'Intel', 'Coca-Cola', 'Wells Fargo', 'AT&T', 'General Electric', 'Oracle', 'Citigroup', 'IBM', 'Philip Morris Int.', 'Cisco Systems', 'Merck', 'PepsiCo', 'AIG', 'Amgen', 'UPS', 'Bristol-Myers Squibb', 'Qualcomm', 'Loews', 'Raytheon', 'McDonald’s', 'Boeing', '3M', 'Altria Group']

data = {
    'name': [
        'Apple', 'Alphabet', 'Microsoft', 'Amazon', 'NVIDIA', 'Meta', 'Tesla',
        'Berkshire Hathaway', 'Eli Lilly', 'Visa', 'Broadcom', 'JPMorgan Chase',
        'UnitedHealth', 'Walmart', 'Mastercard', 'Exxon Mobil', 'Johnson & Johnson',
        'Procter & Gamble', 'Home Depot', 'Costco', 'Chevron', 'Bank of America',
        'Pfizer', 'Walt Disney', 'PayPal', 'Verizon', 'Intel', 'Coca-Cola',
        'Wells Fargo', 'AT&T', 'General Electric', 'Oracle', 'Citigroup', 'IBM',
        'Philip Morris Int.', 'Cisco Systems', 'Merck', 'PepsiCo', 'AIG', 'Amgen',
        'UPS', 'Bristol-Myers Squibb', 'Qualcomm', 'Loews', 'Raytheon', 'McDonald’s',
        'Boeing', '3M', 'Altria Group'
    ],
    'ticker': [
        'AAPL', 'GOOG', 'MSFT', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK-B', 'LLY', 'V',
        'AVGO', 'JPM', 'UNH', 'WMT', 'MA', 'XOM', 'JNJ', 'PG', 'HD', 'COST', 'CVX',
        'BAC', 'PFE', 'DIS', 'PYPL', 'VZ', 'INTC', 'KO', 'WFC', 'T', 'GE', 'ORCL',
        'C', 'IBM', 'PM', 'CSCO', 'MRK', 'PEP', 'AIG', 'AMGN', 'UPS', 'BMY', 'QCOM',
        'L', 'RTX', 'MCD', 'BA', 'MMM', 'MO'
    ],
   'ipo': [1980, 2004, 1986, 1997, 1999, 2012, 2010, 1965, 1952, 2008, 2009, 1969, 1984, 1970, 2006, 1972, 1944, 1890, 1981, 1985, 1926, 1971, 1942, 1957, 2002, 2000, 1971, 1919, 1978, 1984, 1892, 1986, 1986, 1916, 2008, 1990, 1970, 1965, 1969, 1983, 1999, 1933, 1991, 1969, 1980, 1965, 1962, 1946, 2008]
}


# Converte i dati in un DataFrame
df = pd.DataFrame(data)



# Create input fields for stock symbols and moving averages
col1, = st.columns(1)
with col1:
    stock_input = st.multiselect("Select stocks:", options=df['name'])
   
# Filtra i dati corrispondenti ai titoli selezionati
    selected_stocks = df[df['name'].isin(stock_input)]
    selected_tickers = selected_stocks['ticker'].tolist()
    max_ipo_year = selected_stocks['ipo'].max()  # Anno di IPO più recente

    # Inizializza un DataFrame vuoto per raccogliere i dati
    combined_data = pd.DataFrame()

try:
    for ticker in selected_tickers:
           stock = yf.Ticker(ticker)
           hist = stock.history(start=f"{max_ipo_year}-01-01")  # Filtra dall'anno più recente
           hist['Ticker'] = ticker  # Aggiunge una colonna per identificare il titolo
           combined_data = pd.concat([combined_data, hist])

    # Riorganizza i dati per costruire il portafoglio
    pivot_data = combined_data.pivot_table(values='Close', index=combined_data.index, columns='Ticker')

    # Calcola i pesi equamente distribuiti
    num_stocks = len(selected_tickers)
    weights = [1 / num_stocks] * num_stocks

    # Calcola il valore giornaliero del portafoglio
    portfolio_values = pivot_data.dot(weights)

    # Crea un DataFrame per il portafoglio
    portfolio_df = pd.DataFrame({
        'Date': portfolio_values.index,
        'Value': portfolio_values
    }).set_index('Date')


    portfolio_df.dropna(inplace=True)  # Rimuove le righe con NaN


    st.write("Ecco un'anteprima di portfolio_df:")
    st.dataframe(portfolio_df)

    st.write(portfolio_df.head())
    st.write(portfolio_df.columns)
    if portfolio_df.index.name == 'Date':
        portfolio_df = portfolio_df.reset_index()

    portfolio_df['Date'] = pd.to_datetime(portfolio_df['Date']).dt.date
    portfolio_df['Date'] = portfolio_df['Date'].astype(str)
    st.write(portfolio_df['Date'].head())


    st.write(portfolio_df.head())
    st.write(portfolio_df.columns)


# Create the base figure
    fig = go.Figure()

    st.write("1111111111111")
    # Create frames for animation
    frames = [
        go.Frame(
            data=[
                go.Scatter(x=portfolio_df['Date'][:k+1], y=portfolio_df['Value'][:k+1], mode='lines', name='Value')
            ],
            name=str(k)
        ) for k in range(len(portfolio_df))
    ]

    st.write("222222222222")
    # Add the first frame manually to ensure the initial display
    fig.add_trace(go.Scatter(x=portfolio_df['Date'][:1], y=portfolio_df['Value'][:1], mode='lines', name='Value'))

    st.write("3333333333333")

    # Update the layout with frames and animation settings
    fig.update_layout(
        xaxis=dict(range=[portfolio_df['Date'].min(), portfolio_df['Date'].max()], title='Date'),
        yaxis=dict(range=[portfolio_df['Value'].min(), portfolio_df['Value'].max()], title='Price ($)'),
        title="Share Prices",
      
       
        updatemenus=[dict(type="buttons", showactive=False,
                          buttons=[dict(label="Play",
                                        method="animate",
                                        args=[None, {"frame": {"duration": 20, "redraw": True},
                                                     "fromcurrent": True, "mode": "immediate"}])])],
        sliders=[{
            "steps": [{"args": [[str(k)], {"frame": {"duration": 20, "redraw": True}, "mode": "immediate"}],
                       "label": str(portfolio_df['Date'][k].date()), "method": "animate"} for k in range(len(portfolio_df))],
            "transition": {"duration": 0},
            "x": 0.1,
            "len": 0.9
        }]
    )

    st.write("4444444444")
    # Add frames to the figure
    fig.frames = frames

    # Display the Plotly figure in Streamlit
    st.plotly_chart(fig)

   

except Exception as e:
    st.error(f"Error fetching data for . Please check the stock symbol and try again.")
    st.error(f"Error details: {str(e)}")
