# -*- coding: utf-8 -*-
"""Copia di AnimatedStock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zp8CtW2r6cNFTZkM0YePUav7Vsy5Pl11
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go

# Set the title of the Streamlit app
st.title("Stock Prices with Animation")


data = {
    'name': [
        'Apple', 'Alphabet', 'Microsoft', 'Amazon', 'NVIDIA', 'Meta', 'Tesla',
        'Berkshire Hathaway', 'Eli Lilly', 'Visa', 'Broadcom', 'JPMorgan Chase',
        'UnitedHealth', 'Walmart', 'Mastercard', 'Exxon Mobil', 'Johnson & Johnson',
        'Procter & Gamble', 'Home Depot', 'Costco', 'Chevron', 'Bank of America',
        'Pfizer', 'Walt Disney', 'PayPal', 'Verizon', 'Intel', 'Coca-Cola',
        'Wells Fargo', 'AT&T', 'General Electric', 'Oracle', 'Citigroup', 'IBM',
        'Philip Morris Int.', 'Cisco Systems', 'Merck', 'PepsiCo', 'AIG', 'Amgen',
        'UPS', 'Bristol-Myers Squibb', 'Qualcomm', 'Loews', 'Raytheon', 'McDonald’s',
        'Boeing', '3M', 'Altria Group'
    ],
    'ticker': [
        'AAPL', 'GOOG', 'MSFT', 'AMZN', 'NVDA', 'META', 'TSLA', 'BRK-B', 'LLY', 'V',
        'AVGO', 'JPM', 'UNH', 'WMT', 'MA', 'XOM', 'JNJ', 'PG', 'HD', 'COST', 'CVX',
        'BAC', 'PFE', 'DIS', 'PYPL', 'VZ', 'INTC', 'KO', 'WFC', 'T', 'GE', 'ORCL',
        'C', 'IBM', 'PM', 'CSCO', 'MRK', 'PEP', 'AIG', 'AMGN', 'UPS', 'BMY', 'QCOM',
        'L', 'RTX', 'MCD', 'BA', 'MMM', 'MO'
    ],
   'ipo': [1980, 2004, 1986, 1997, 1999, 2012, 2010, 1965, 1952, 2008, 2009, 1969, 1984, 1970, 2006, 1972, 1944, 1890, 1981, 1985, 1926, 1971, 1942, 1957, 2002, 2000, 1971, 1919, 1978, 1984, 1892, 1986, 1986, 1916, 2008, 1990, 1970, 1965, 1969, 1983, 1999, 1933, 1991, 1969, 1980, 1965, 1962, 1946, 2008]
}


# Converte i dati in un DataFrame
df = pd.DataFrame(data)
# Inizializza un DataFrame vuoto per raccogliere i dati
combined_data = pd.DataFrame()

# Create input fields for stock symbols and moving averages

# Menu a tendina per selezionare più titoli

stock_input = st.multiselect("Select stocks:", options=df['name'])
selected_stocks = df[df['name'].isin(stock_input)]
selected_tickers = selected_stocks['ticker']
selected_stock = selected_tickers

max_ipo_year = selected_stocks['ipo'].max()+1  # Anno di IPO più recente

st.write(max_ipo_year)

for ticker in selected_tickers:
    # Fetch stock data for the selected symbol
        stock = yf.Ticker(ticker)
        #hist = stock.history(start="2019-02-01", interval="1wk") #funzionante, prob non riesce a fre grafici con troppi punti
        #hist = stock.history(period="max",interval="1wk" ) #funzionante
        hist1 = stock.history(start=f"{max_ipo_year}-01-01",interval="1wk" )
        hist1['Ticker'] = ticker  # Aggiunge una colonna per identificare il titolo
        combined_data = pd.concat([combined_data, hist1])

st.write("Ecco un'anteprima di combined_data:")
st.dataframe(combined_data)

   # Calcola il numero di titoli
num_tickers = len(selected_tickers)

# Calcola i ritorni settimanali per ogni ticker
combined_data['Return'] = combined_data.groupby('Ticker')['Close'].pct_change()

st.write("Ecco un'anteprima di combined_data con return:")
st.dataframe(combined_data)


returns = combined_data.pivot_table(
    index='Date',
    columns='Ticker',
    values='Return',
    aggfunc='mean'  # In caso di duplicati, calcola la media dei ritorni
)




# Pivot dei dati per ottenere una matrice di ritorni
#returns = combined_data.pivot(index='Date', columns='Ticker', values='Return')

st.write("Ecco un'anteprima di returns:")
st.dataframe(returns)

# Calcola i ritorni cumulativi
cumulative_returns = (1 + returns).cumprod()

# Portafoglio equally weighted
portfolio_weights = [1/num_tickers] * num_tickers
portfolio_cumulative_returns = (cumulative_returns * portfolio_weights).sum(axis=1)



st.write("Ecco un'anteprima di portfolio_cumulative_returns:")
st.dataframe(portfolio_cumulative_returns)

   



hist=portfolio_cumulative_returns
    # Create the base figure
fig = go.Figure()

    # Create frames for animation
frames = [
        go.Frame(
            data=[
                go.Scatter(x=hist['Date'][:k+1], y=hist['Close'][:k+1], mode='lines', name='Close Price')
            ],
            name=str(k)
        ) for k in range(len(hist))
    ]

    # Add the first frame manually to ensure the initial display
fig.add_trace(go.Scatter(x=hist['Date'][:1], y=hist['Close'][:1], mode='lines', name='Close Price'))
    

    # Update the layout with frames and animation settings
fig.update_layout(
        xaxis=dict(range=[hist['Date'].min(), hist['Date'].max()], title='Date'),
        yaxis=dict(range=[hist['Close'].min(), hist['Close'].max()], title='Price ($)'),
        title=f"{selected_stock} Share Prices with",
        updatemenus=[dict(type="buttons", showactive=False,
                          buttons=[dict(label="Play",
                                        method="animate",
                                        args=[None, {"frame": {"duration": 1, "redraw": False},
                                                     "fromcurrent": True, "mode": "immediate"}])])],
        sliders=[{
            "steps": [{"args": [[str(k)], {"frame": {"duration": 1, "redraw": False}, "mode": "immediate"}],
                       "label": str(hist['Date'][k].date()), "method": "animate"} for k in range(len(hist))],
            "transition": {"duration": 0},
            "x": 0.1,
            "len": 0.9
        }]
    )

    # Add frames to the figure
fig.frames = frames

    # Display the Plotly figure in Streamlit
st.plotly_chart(fig)


