# -*- coding: utf-8 -*-
"""gioco borsa stream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1esFTH_d8I7DXSsfsSpOoHUSKlVaDHfle
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go

# Set the title of the Streamlit app
st.title("Try to beat the market")





